
enum AnimalsEasingType {
    EASE_IN_CIRC,
    EASE_IN_SINE,
    EASE_IN_QUINT,
    EASE_IN_CUBIC,
    EASE_IN_QUAD,
    EASE_IN_QUART,
    EASE_IN_EXPO,
    EASE_OUT_CIRC,
    EASE_OUT_SINE,
    EASE_OUT_QUINT,
    EASE_OUT_CUBIC,
    EASE_OUT_QUAD,
    EASE_OUT_QUART,
    EASE_OUT_EXPO,
    NONE
}