<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>RPGCreator.Tests</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RPGCreator.Core\RPGCreator.Core.csproj" />
      <ProjectReference Include="..\RPGCreator.SDK\RPGCreator.SDK.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Registries\" />
    </ItemGroup>
</Project>
