<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Remove="Content\AssetsManage\AssetsEditors\AutotileEditor\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Remove="Assets\rpgc-logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\TMGrammar\RPGFormula.tmLanguage.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\rpgc-logo.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
      <ProjectReference Include="..\RPGCreator.Generators\RPGCreator.Generators.csproj">
          <OutputItemType>Analyzer</OutputItemType>
          <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.6" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="11.3.0" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.6" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="11.3.6" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.6" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.6" />
    <PackageReference Include="AvaloniaEdit.TextMate" Version="11.3.0" />
    <PackageReference Include="AvaloniaInside.MonoGame" Version="1.0.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />

    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.6" />
    <PackageReference Include="Irihi.Ursa" Version="1.12.0" />
    <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="1.12.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageReference Include="Projektanker.Icons.Avalonia" Version="9.6.2" />
    <PackageReference Include="Projektanker.Icons.Avalonia.MaterialDesign" Version="9.6.2" />
    <PackageReference Include="Semi.Avalonia" Version="11.2.1.6" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Lang\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Remove="Content\AssetsManage\AssetsEditors\AutotileEditor\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Icons\" />
    <Folder Include="Common\AnimEditor\" />
    <Folder Include="Content\AssetsManage\Components\Items\" />
    <Folder Include="Content\Editor\RightPanel\" />
    <Folder Include="Content\Preferences\Components\General\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RPGCreator.RTP\RPGCreator.RTP.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Lang\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Remove="Content\AssetsManage\AssetsEditors\AutotileEditor\**" />
  </ItemGroup>
	<ItemGroup>
	  <Compile Update="Resources.Designer.cs">
		<DesignTime>True</DesignTime>
		<AutoGen>True</AutoGen>
		<DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <UpToDateCheckInput Remove="OldUI\Views\Editor\Editor.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Editor\EditorView.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Editor\EditorView\Tabs\LevelEditorTab.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Editor\Templates\Tileset_asset_item.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Editor\Windows\ProjectSettings.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Editor\Windows\ProjectSettings\AssetsTilesets.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Editor\Windows\ProjectSettings\Dialogs\TilesetDeleteDialog.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Editor\Windows\ProjectSettings\Dialogs\TilesetEditDialog.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Editor\Windows\ProjectSettings\Dialogs\TilesetImportDialog.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Editor\Windows\ProjectSettings\Information.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Editor\Windows\ProjectSettings\Test.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Launcher\Templates\ProjectItem.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Launcher\Windows\ProjectCreator\ProjectCreatorView.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Launcher\Windows\ProjectCreator\ProjectCreatorWindow.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\LauncherView.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\LauncherWindow.axaml" />
	  <UpToDateCheckInput Remove="OldUI\Views\Modals\ErrorDialog.axaml" />
	</ItemGroup>
	<ItemGroup>
	  <AvaloniaXaml Remove="Content\AssetsManage\AssetsEditors\AutotileEditor\**" />
	</ItemGroup>
	<ItemGroup>
	  <AdditionalFiles Remove="Content\AssetsManage\AssetsEditors\AutotileEditor\**" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="Content\AssetsManage\AssetsEditors\AutotileEditor\**" />
	</ItemGroup>

    <Target Name="CopyAssets" AfterTargets="Build">
        <ItemGroup>
            <!-- Tous les fichiers dans le dossier Assets -->
            <AssetFiles Include="Assets\**\*.*" />
        </ItemGroup>

        <Copy SourceFiles="@(AssetFiles)"
              DestinationFolder="$(OutputPath)Assets\%(RecursiveDir)"
              SkipUnchangedFiles="true" />
    </Target>
</Project>
