// RPG Creator - Open-source RPG Engine.
// (c) 2026 Ward
// 
// This file is part of RPG Creator and is distributed under the Apache 2.0 License.
// You are free to use, modify, and distribute this file under the terms of the Apache 2.0 License.
// See LICENSE for details.
// 
// ---
// 
// Ce fichier fait partie de RPG Creator et est distribué sous licence Apache 2.0.
// Vous êtes libre de l'utiliser, de le modifier et de le distribuer sous les termes de la licence Apache 2.0.
// Voir LICENSE pour plus de détails.
// 
// Contact:
// => Mail: Ward727a@gmail.com
//    Please use this object: "RPG Creator [YourObject]"
// => Discord: ward727
// 
// For urgent inquiries, sending both an email and a message on Discord is highly recommended for a quicker response.

using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace RPGCreator.MainGenerator.Parts;

public static class GenModule
{
    public static void GenerateModuleStarter(SourceProductionContext spc, ImmutableArray<INamedTypeSymbol?> sources)
    {
        var firstSymbol = sources.FirstOrDefault();

        if (firstSymbol is null)
        {
            GeneratorLogger.WarningMisc("No EModuleStarter found in the project! Is it normal?\n" +
                                        "If you do not have the need of EModuleStarter, EClass, or EProperty, you can safely ignore this warning.");
            return;
        }
        
        var stringWriter = new StringWriter(new StringBuilder());
        using var sb = new IndentedTextWriter(stringWriter, "    ");

        var moduleContext = new ModuleGenerationContext(sb);
        
        moduleContext.Writer.WriteLine("// <auto-generated/>");
        moduleContext.Writer.WriteLine();

        moduleContext.Writer.WriteLine("using System;");
        moduleContext.Writer.WriteLine("using RPGCreator.SDK;");
        moduleContext.Writer.WriteLine("using RPGCreator.SDK.Exceptions;");
        moduleContext.Writer.WriteLine("using RPGCreator.SDK.Types;");
        moduleContext.Writer.WriteLine("using RPGCreator.SDK.Types.EngineClass;");
        
        foreach (var ns in ContextGenerator.Namespaces)
        {
            moduleContext.Writer.WriteLine($"using {ns};");
        }
        
        moduleContext.Writer.WriteLine($"namespace {firstSymbol.ContainingNamespace}");
        moduleContext.Writer.WriteLine("{");
        moduleContext.Indent++;
        
            moduleContext.Writer.WriteLine($"public partial class {firstSymbol.Name} : EModule");
            moduleContext.Writer.WriteLine("{");
            moduleContext.Indent++;

            moduleContext.Writer.WriteLine("protected void RegisterEClasses()");
            moduleContext.Writer.WriteLine("{");
            moduleContext.Indent++;

            foreach (var classData in ContextGenerator.EClassDataList.Values)
            {
                moduleContext.Writer.WriteLine($"RegistryServices.Classes.Register<{classData.Class.Name}>({classData.Class.Name}.ClassUrn, {classData.Class.Name}.Create).OnFailure(e => throw new Exception($\"Error while registering classes for module entry \\\"{firstSymbol.Name}\\\"{{e}}\"));");
            }
            
            moduleContext.Indent--;
            moduleContext.Writer.WriteLine("}");
            
            moduleContext.Writer.WriteLine("protected void UnregisterEClasses()");
            moduleContext.Writer.WriteLine("{");
            moduleContext.Indent++;
            
            foreach (var classData in ContextGenerator.EClassDataList.Values)
            {
                moduleContext.Writer.WriteLine($"RegistryServices.Classes.Unregister({classData.Class.Name}.ClassUrn).OnFailure(e => throw new Exception($\"Error while un-registering classes for module entry \\\"{firstSymbol.Name}\\\"{{e}}\"));");
            }
            moduleContext.Indent--;
            moduleContext.Writer.WriteLine("}");
            
            
            moduleContext.Indent--;
            moduleContext.Writer.WriteLine("}");
        
        moduleContext.Indent--;
        moduleContext.Writer.WriteLine("}");
        
        spc.AddSource($"{firstSymbol.Name}.g.cs", stringWriter.ToString());
    }
}