// RPG Creator - Open-source RPG Engine.
// (c) 2026 Ward
// 
// This file is part of RPG Creator and is distributed under the Apache 2.0 License.
// You are free to use, modify, and distribute this file under the terms of the Apache 2.0 License.
// See LICENSE for details.
// 
// ---
// 
// Ce fichier fait partie de RPG Creator et est distribué sous licence Apache 2.0.
// Vous êtes libre de l'utiliser, de le modifier et de le distribuer sous les termes de la licence Apache 2.0.
// Voir LICENSE pour plus de détails.
// 
// Contact:
// => Mail: Ward727a@gmail.com
//    Please use this object: "RPG Creator [YourObject]"
// => Discord: ward727
// 
// For urgent inquiries, sending both an email and a message on Discord is highly recommended for a quicker response.

using Microsoft.CodeAnalysis;

namespace RPGCreator.MainGenerator.Parts;

public static class GenNamespaces
{
    private static readonly string[] Namespaces =
    [
        "System", "System.Collections.Generic", "System.Diagnostics.CodeAnalysis", 
        "System.Text.Json", "System.Text.Json.Serialization",
        "RPGCreator.SDK", "RPGCreator.SDK.GameUI", "RPGCreator.SDK.GameUI.Interfaces", 
        "RPGCreator.SDK.Types", "RPGCreator.SDK.Types.EngineClass", "RPGCreator.SDK.Projects"
    ];


    public static void Begin(GenerationContext context)
    {
        var baseNamespace = context.ClassData.Class.ContainingNamespace.ToDisplayString(
            SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle
                .OmittedAsContaining));
        
        context.Writer.WriteLine("// <auto-generated/>");
        foreach (var ns in Namespaces)
        {
            context.Writer.WriteLine($"using {ns};");
        }
        
        context.Writer.WriteLine();
        
        context.Writer.WriteLine($"namespace {baseNamespace}");
        context.Writer.WriteLine("{");
        context.Indent++;
    }

    public static string GetNamespace(GenerationContext context)
    {
        return context.ClassData.Class.ContainingNamespace.ToDisplayString(
            SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle
                .OmittedAsContaining));
    }

    public static void End(GenerationContext context)
    {
        context.Indent--;
        context.Writer.WriteLine("}");
    }
}