#region LICENSE
//
// RPG Creator - Open-source RPG Engine.
// (c) 2025 Ward
// 
// This file is part of RPG Creator and is distributed under the MIT License.
// You are free to use, modify, and distribute this file under the terms of the MIT License.
// See LICENSE for details.
// 
// ---
// 
// Ce fichier fait partie de RPG Creator et est distribué sous licence MIT.
// Vous êtes libre de l'utiliser, de le modifier et de le distribuer sous les termes de la licence MIT.
// Voir LICENSE pour plus de détails.
// 
// Contact:
// => Mail: Ward727a@gmail.com
//    Please use this object: "RPG Creator [YourObject]"
// => Discord: ward727
// 
// For urgent inquiries, sending both an email and a message on Discord is highly recommended for a quicker response.
// 
// 
#endregion
using CommunityToolkit.Mvvm.ComponentModel;
using RPGCreator.Core.Configs.EventsArgs;
using RPGCreator.Core.Configs.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace RPGCreator.Core.Configs
{
    public class EngineConfigs
    {

        public EngineConfigEvents Events { get; private set; }

        public static string CONF_WARN_TEMPLATE = @"
<!-- ============================ -->
<!-- GENERATED FILE - DO NOT EDIT -->
<!-- ============================ -->
<!-- This file has been generated by RPG Creator, and it should be manually edited ONLY if you know what you are doing at the risk of losing data. -->";

        readonly string APP_CONF_TEMPLATE = $@"
{CONF_WARN_TEMPLATE}
<!-- Dev note: Format for the path: %APPDIR% => Folder where the .exe of the editor is found | %APPDATA% => Folder ""RPG Creator"" found in the user %APPDATA% folder. -->
<!-- No ""/"" is added after the %APPDATA% or %APPDIR%, so you need to add a ""/"" after the last ""%"" -->
<Config configClass=""{typeof(AppConf).AssemblyQualifiedName}"" configName=""AppConf"">
    <ConfigPath>
        <Projects>%APPDATA%/Configs/</Projects>
        <Style>%APPDATA%/Configs/</Style>
        <Assets>%APPDATA%/Assets/</Assets>
    </ConfigPath>
</Config>
";

        readonly string PROJECT_CONF_TEMPLATE = $@"
{CONF_WARN_TEMPLATE}
<!-- Dev note: The Tags element found at the bottom is here to save each user tag, with color and name. -->
<Projects configClass=""{typeof(ProjectsConf).AssemblyQualifiedName}"" configName=""ProjectsConf"">

<Tags/>
</Projects>
";

        readonly string STYLE_CONF_TEMPLATE = $@"
{CONF_WARN_TEMPLATE}
<!-- Dev note: This file is still in WIP stage, it's currently not used by the engine! -->
<Style customClass=""{typeof(StyleConf).AssemblyQualifiedName}"" configName=""StyleConf"">
    <Launcher>
        <ProjectItemBackground>#10FFFFFF</ProjectItemBackground>
    </Launcher>
</Style>
";

        private Dictionary<string, ConfHelper> LoadedConfig = [];
        private Dictionary<string, string> ConfigMap = []; // Map of the config path to the config name

        internal EngineConfigs()
        {
            Events = new EngineConfigEvents();
            // Load the default config file that should be inside the folder where the .exe is
            var t = AppDomain.CurrentDomain.BaseDirectory;
            LoadOrCreateConfig(
                Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "App.conf.xml"),
                APP_CONF_TEMPLATE,
                true
            );

            LoadOrCreateConfig(
                Path.Combine(((AppConf)LoadedConfig["AppConf"]).ConfigPath.ProjectsFolder, "Projects.conf.xml"),
                PROJECT_CONF_TEMPLATE,
                true
            );
        }

        private bool TryResolveCustomType(string typeName, out System.Type? type, out string? error)
        {
            type = System.Type.GetType(typeName);
            if (type == null)
            {
                error = $"Custom type '{typeName}' not found.";
                return false;
            }
            if (!typeof(ConfHelper).IsAssignableFrom(type))
            {
                error = $"Custom type '{typeName}' is not a valid ConfHelper.";
                return false;
            }
            error = null;
            return true;
        }

        public bool LoadOrCreateConfig(string configPath, string template, bool force = false)
        {
            var PreArgsLoad = new LoadingConfigArgs(configPath);
            Events.OnLoadingConfig(PreArgsLoad);

            if(PreArgsLoad.Cancel)
                return false;

            configPath = PreArgsLoad.ConfigPath;

            string configName = Path.GetFileNameWithoutExtension(configPath);

            if (LoadedConfig.ContainsKey(configName) && !force)
                return true;
            else if (LoadedConfig.ContainsKey(configName) && force)
            {
                LoadedConfig.Remove(configName);

                var mapList = ConfigMap.Where(cm => cm.Value == configName).ToList();

                if(mapList.Count == 1)
                    ConfigMap.Remove(mapList[0].Key);
                else
                { 
                    Events.OnLoadedConfig(PreArgsLoad.ToPost(configName).SetError(true, $"Config {configName} is not found in the ConfigMap, or it was found for mutliple key."));
                    EngineCore.Instance.Events.OnCoreError(new() { Level = Core.Events.EventArgs.BaseErrorArgs.ERROR_LEVEL.FATAL, Description = $"Config {configName} is not found in the ConfigMap, or it was found for mutliple key." });
                    return false;
                }
            }

            if (!File.Exists(configPath))
            {
                var PreArgsCreate = new CreatingConfigArgs(configPath, template);
                Events.OnCreatingConfig(PreArgsCreate);
                
                string directory = Path.GetDirectoryName(configPath) ?? "";
                if(!Directory.Exists(directory))
                {
                    try
                    {
                        Directory.CreateDirectory(directory);
                    }
                    catch (Exception ex)
                    {
                        Events.OnCreatedConfig(PreArgsCreate.ToPost().SetError(true, ex.Message));
                        return false;
                    }
                }
                
                configPath = PreArgsCreate.ConfigPath;
                template = PreArgsCreate.ConfigContent;
                try
                {
                    File.WriteAllText(configPath, template);
                    Events.OnCreatedConfig(PreArgsCreate.ToPost());
                }
                catch (Exception ex)
                {
                    Events.OnCreatedConfig(PreArgsCreate.ToPost().SetError(true, ex.Message));
                    return false;
                }
            }

            XDocument? doc = null;

            try
            {
                doc = XDocument.Load(configPath);
            }
            catch (Exception ex)
            {
                Events.OnLoadedConfig(PreArgsLoad.ToPost().SetError(true, ex.Message));
                return false;
            }


            if (doc.Root == null)
            {
                Events.OnLoadedConfig(PreArgsLoad.ToPost().SetError(true, $"XML Document at {configPath} doesn't contain a root element."));
                return false;
            }

            var configNameAttr = doc.Root.Attribute("configName");
            var customClassAttr = doc.Root.Attribute("configClass");


            if (configNameAttr == null ||
                string.IsNullOrEmpty(configNameAttr!.Value))
            {
                doc.Root.SetAttributeValue("configName", configName);
                doc.Save(configPath);
            }
            else
            {
                configName = configNameAttr!.Value;
            }
            if (LoadedConfig.ContainsKey(configName) && !force)
                return true;
            else if (LoadedConfig.ContainsKey(configName) && force)
            {
                LoadedConfig.Remove(configName);

                var mapList = ConfigMap.Where(cm => cm.Value == configName).ToList();

                if (mapList.Count == 1)
                    ConfigMap.Remove(mapList[0].Key);
                else
                {
                    Events.OnLoadedConfig(PreArgsLoad.ToPost(configName).SetError(true, $"Config {configName} is not found in the ConfigMap, or it was found for multipe key."));
                    EngineCore.Instance.Events.OnCoreError(new() { Level = Core.Events.EventArgs.BaseErrorArgs.ERROR_LEVEL.FATAL, Description = $"Config {configName} is not found in the ConfigMap, or it was found for multipe key." });
                    return false;
                }
            }

            if (
                customClassAttr == null || 
                string.IsNullOrEmpty(customClassAttr!.Value))
            {
                LoadedConfig.Add(configName, new ConfHelper() { Doc = doc, ConfigPath = configPath });
                ConfigMap.Add(configPath, configName);
                Events.OnLoadedConfig(PreArgsLoad.ToPost(configName));
                return true;
            }
            else
            {
                string customClass = customClassAttr!.Value;

                bool typeResolved = TryResolveCustomType(customClass, out System.Type? type, out string? error);

                if (!typeResolved || type == null)
                {
                    Events.OnLoadedConfig(PreArgsLoad.ToPost(configName).SetError(true, $"XML Document at {configPath} defines a customClass '{customClass}' but got error: {error}"));
                    return false;
                }

                object? obj = Activator.CreateInstance(type);

                if(obj == null)
                {
                    Events.OnLoadedConfig(PreArgsLoad.ToPost(configName).SetError(true, $"XML Document at {configPath} defines a customClass '{customClass}' but it couldn't be created."));
                    return false;
                }
                ConfHelper conf = (ConfHelper)obj;
                conf.Doc = doc;
                conf.ConfigPath = configPath;
                conf.SetType(type);
                conf.LoadConfig();

                LoadedConfig.Add(configName, conf);
                ConfigMap.Add(configPath, configName);
                Events.OnLoadedConfig(PreArgsLoad.ToPost(configName));
                return true;
            }
        }

        public bool LoadConfig(string configPath)
        {

            if(ConfigMap.ContainsKey(configPath))
                return true;

            var doc = XDocument.Load(configPath);

            if (doc.Root == null)
                return false;

            if (doc.Root.Attribute("configName") == null ||
                string.IsNullOrEmpty(doc.Root.Attribute("configName")!.Value))
            {
                doc.Root.SetAttributeValue("configName", Path.GetFileName(configPath).Split(".")[0]);
            }

            if (doc.Root.Attribute("configClass") == null ||
                string.IsNullOrEmpty(doc.Root.Attribute("customClass")!.Value))
            {
                LoadedConfig.Add(configPath, new ConfHelper() { Doc = doc, ConfigPath = configPath });
                ConfigMap.Add(configPath, Path.GetFileName(configPath).Split(".")[0]);
                return true;
            }
            else
            {
                string customClass = doc.Root.Attribute("customClass")!.Value;
                System.Type? type = System.Type.GetType(customClass);
                if (type == null)
                    return false;
                if (!typeof(ConfHelper).IsAssignableFrom(type))
                    return false;
                object? obj = Activator.CreateInstance(type);
                if (obj == null)
                    return false;
                ConfHelper conf = (ConfHelper)obj;
                conf.SetType(type);
                conf.ConfigPath = configPath;
                conf.LoadConfig();
                LoadedConfig.Add(configPath, conf);
                ConfigMap.Add(configPath, Path.GetFileName(configPath).Split(".")[0]);
                return true;
            }
        }

        public ConfHelper? GetConfig(string configName)
        {
            if (LoadedConfig.ContainsKey(configName))
            {
                return LoadedConfig[configName];
            }
            else
            {
                return null;
            }
        }

        public T? GetConfig<T>(string configName) where T : ConfHelper
        {
            if (LoadedConfig.ContainsKey(configName))
            {
                if (LoadedConfig[configName] is T conf)
                {
                    return conf;
                }
                else
                {
                    return null;
                }
            }
            else
            {
                return null;
            }
        }

        public string GetPath(string config)
        {
            var mapList = ConfigMap.Where(cm => cm.Value == config).ToList();

            if (mapList.Count == 1)
                return mapList[0].Key;
            else
                return "";
        }

        public bool Save(string config)
        {

            var preArgs = new SavingConfigArgs(config);
            Events.OnSavingConfig(preArgs);

            if(preArgs.Cancel)
                return false;

            config = preArgs.ConfigName;

            if (LoadedConfig.ContainsKey(config))
            {
                if (LoadedConfig[config] is ConfHelper conf)
                {
                    conf.Save();
                    Events.OnSavedConfig(preArgs.ToPost());
                    return true;
                }
                else
                {
                    string path = GetPath(config);

                    if (string.IsNullOrEmpty(path))
                    {
                        Events.OnSavedConfig(preArgs.ToPost().SetError(true, $"Config {config} is not found in the ConfigMap."));
                        return false;
                    }

                    LoadedConfig[config].Save(path);
                    Events.OnSavedConfig(preArgs.ToPost());
                    return true;
                }
            }
            else
            {
                Events.OnSavedConfig(preArgs.ToPost().SetError(true, $"Config {config} is not found in the LoadedConfig."));
                return false;
            }

        }

        public bool SaveAll()
        {
            foreach (var config in LoadedConfig.Keys)
            {
                if(!Save(config))
                {
                    return false;
                }
            }
            return true;
        }

        public bool Export(string config, string export_path)
        {
            var preArgs = new ExportingConfigArgs(config, export_path);
            Events.OnExportingConfig(preArgs);

            if (preArgs.Cancel)
                return false;

            config = preArgs.ConfigName;
            export_path = preArgs.ExportPath;

            if (LoadedConfig.ContainsKey(config))
            {
                LoadedConfig[config].Save(export_path);
                Events.OnExportedConfig(preArgs.ToPost());
                return true;
            }
            else
            {
                Events.OnExportedConfig(preArgs.ToPost().SetError(true, $"Config {config} is not found in the LoadedConfig."));
                return false;
            }
        }

        /// <summary>
        /// This class should ONLY be inherited for config helper.
        /// </summary>
        public class ConfHelper
        {
            public XDocument Doc { get; internal set; }
            public string ConfigPath = "";
            public XElement Root => Doc.Root!;
            public System.Type? CustomType { get; private set; }
            public bool HasCustomType => CustomType != null;

            public void SetType(System.Type type)
            {
                CustomType = type;
            }

            public void Save(string path)
            {
                Doc.Save(path);
            }

            public virtual void LoadConfig() { }

            public virtual void Save() { }
        }
    }
}
