//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGCreator.UI.OLD.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPGCreator.UI.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a project....
        /// </summary>
        public static string Launcher_InputSearchProject {
            get {
                return ResourceManager.GetString("Launcher.InputSearchProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string Launcher_NewProject {
            get {
                return ResourceManager.GetString("Launcher.NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your first project!.
        /// </summary>
        public static string Launcher_NewProjectIfNone {
            get {
                return ResourceManager.GetString("Launcher.NewProjectIfNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any project.. For now..
        /// </summary>
        public static string Launcher_NoProjectFound {
            get {
                return ResourceManager.GetString("Launcher.NoProjectFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder....
        /// </summary>
        public static string Launcher_OpenFolder {
            get {
                return ResourceManager.GetString("Launcher.OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add author.
        /// </summary>
        public static string Launcher_ProjectCreator_AddAuthor {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.AddAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        public static string Launcher_ProjectCreator_CreateProjectButton {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.CreateProjectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another project as the same name, choose another one..
        /// </summary>
        public static string Launcher_ProjectCreator_ErrorNameTaken {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.ErrorNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project name has been provided..
        /// </summary>
        public static string Launcher_ProjectCreator_ErrorNoName {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.ErrorNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No path has beend provided..
        /// </summary>
        public static string Launcher_ProjectCreator_ErrorNoPath {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.ErrorNoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided path is not valid..
        /// </summary>
        public static string Launcher_ProjectCreator_ErrorPathInvalid {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.ErrorPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided path point to a not empty folder..
        /// </summary>
        public static string Launcher_ProjectCreator_ErrorPathNotEmpty {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.ErrorPathNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author of the project....
        /// </summary>
        public static string Launcher_ProjectCreator_HintAuthor {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.HintAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put the project description here....
        /// </summary>
        public static string Launcher_ProjectCreator_HintDesc {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.HintDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put the project name here....
        /// </summary>
        public static string Launcher_ProjectCreator_HintName {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.HintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a path to save your project.
        /// </summary>
        public static string Launcher_ProjectCreator_HintPath {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.HintPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: This feature allows you to select a license for your project, but it does not constitute legal advice in any way..
        /// </summary>
        public static string Launcher_ProjectCreator_InfoCopyright {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.InfoCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author(s):.
        /// </summary>
        public static string Launcher_ProjectCreator_LabelAuthors {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.LabelAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright:.
        /// </summary>
        public static string Launcher_ProjectCreator_LabelCopyright {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.LabelCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Launcher_ProjectCreator_LabelDesc {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.LabelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Launcher_ProjectCreator_LabelName {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string Launcher_ProjectCreator_LabelPath {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.LabelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag(s):.
        /// </summary>
        public static string Launcher_ProjectCreator_LabelTags {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.LabelTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Launcher_ProjectCreator_SepOptional {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.SepOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Launcher_ProjectCreator_SepRequired {
            get {
                return ResourceManager.GetString("Launcher.ProjectCreator.SepRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Launcher_Settings {
            get {
                return ResourceManager.GetString("Launcher.Settings", resourceCulture);
            }
        }
    }
}
