#region LICENSE
//
// RPG Creator - Open-source RPG Engine.
// (c) 2025 Ward
// 
// This file is part of RPG Creator and is distributed under the MIT License.
// You are free to use, modify, and distribute this file under the terms of the MIT License.
// See LICENSE for details.
// 
// ---
// 
// Ce fichier fait partie de RPG Creator et est distribué sous licence MIT.
// Vous êtes libre de l'utiliser, de le modifier et de le distribuer sous les termes de la licence MIT.
// Voir LICENSE pour plus de détails.
// 
// Contact:
// => Mail: Ward727a@gmail.com
//    Please use this object: "RPG Creator [YourObject]"
// => Discord: ward727
// 
// For urgent inquiries, sending both an email and a message on Discord is highly recommended for a quicker response.
// 
// 
#endregion
using Avalonia.Media;
using CommunityToolkit.Mvvm.ComponentModel;
using Microsoft.Extensions.DependencyInjection;
using RPGCreator.Core.Internal;
using RPGCreator.Core.Services.Configurations;
using RPGCreator.UI;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Xml.Linq;

/*
 * RPG Creator - Open-source RPG Engine.
 * (c) 2025 Ward
 * 
 * This file is part of RPG Creator and is distributed under the MIT License.
 * You are free to use, modify, and distribute this file under the terms of the MIT License.
 * See LICENSE for details.
 * 
 * ---
 * 
 * Ce fichier fait partie de RPG Creator et est distribué sous licence MIT.
 * Vous êtes libre de l'utiliser, de le modifier et de le distribuer sous les termes de la licence MIT.
 * Voir LICENSE pour plus de détails.
 */

namespace RPGCreator.Core.Services
{
    public class ConfigurationService
    {
        private readonly string APP_DIR;
        private readonly string APPDATA;

        public static string CONF_WARN_TEMPLATE = @"
<!-- ============================ -->
<!-- GENERATED FILE - DO NOT EDIT -->
<!-- ============================ -->
<!-- This file has been generated by RPG Creator, and it should be manually edited ONLY if you know what you are doing at the risk of losing data. -->";

        string APP_CONF_TEMPLATE = $@"
{CONF_WARN_TEMPLATE}
<!-- Dev note: Format for the path: %APPDIR% => Folder where the .exe of the editor is found | %APPDATA% => Folder ""RPG Creator"" found in the user %APPDATA% folder. -->
<!-- No ""/"" is added after the %APPDATA% or %APPDIR%, so you need to add a ""/"" after the last ""%"" -->
<Config customClass=""{typeof(AppConf).AssemblyQualifiedName}"">
    <ConfigPath>
        <Projects>%APPDATA%/Configs/</Projects>
        <Style>%APPDATA%/Configs/</Style>
        <Assets>%APPDATA%/Assets/</Assets>
    </ConfigPath>
</Config>
";

        string PROJECT_CONF_TEMPLATE = $@"
{CONF_WARN_TEMPLATE}
<!-- Dev note: The Tags element found at the bottom is here to save each user tag, with color and name. -->
<Projects customClass=""{typeof(ProjectsConf).AssemblyQualifiedName}"">

<Tags/>
</Projects>
";
        string STYLE_CONF_TEMPLATE = $@"
{CONF_WARN_TEMPLATE}
<!-- Dev note: This file is still in WIP stage, it's currently not used by the engine! -->
<Style customClass=""{typeof(StyleConf).AssemblyQualifiedName}"">
    <Launcher>
        <ProjectItemBackground>#10FFFFFF</ProjectItemBackground>
    </Launcher>
</Style>
";


        public struct CONFIG(XDocument document, string filepath)
        {
            public XDocument Document = document;
            public string Filepath = filepath;
            public bool HasCustomClass = false;
            public System.Type? ClassType;
            public ConfHelper? Class;

            public CONFIG(XDocument document, string filepath, System.Type classType, ConfHelper _class) : this(document, filepath)
            {
                HasCustomClass = true;
                ClassType = classType;
                Class = _class;
            }
        }
        Dictionary<string, CONFIG> Configs = [];

        public ConfigurationService()
        {

            AssetsConf.InitAssetsConf(this);

            APP_DIR = Directory.GetCurrentDirectory();
            APPDATA = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "RPG Creator");
            // Load base config file
            LoadOrMake("app", Path.Combine(APP_DIR, "app.conf.xml"), APP_CONF_TEMPLATE); // This is the only "hardcoded" path for a config file as the engine need to directly know where to find this, to load the custom path.

            // We need this for the next file.
            AppConf app_conf = (AppConf)Configs["app"].Class!;

            LoadOrMake("projects", Path.Combine(app_conf.path.GetProject(), "projects.conf.xml"), PROJECT_CONF_TEMPLATE);
            LoadOrMake("style", Path.Combine(app_conf.path.GetStyle(), "style.conf.xml"), STYLE_CONF_TEMPLATE);
        }

        /// <summary>
        /// Try to get the config object of structure <see cref="CONFIG"/>
        /// </summary>
        /// <param name="key">The config key (e.g. "projects", "app", ...)</param>
        /// <param name="config">The config object if found.</param>
        /// <returns>True if found, false otherwise</returns>
        public bool TryGetConfig(string key, out CONFIG config)
        {
            return Configs.TryGetValue(key, out config);
        }

        /// <summary>
        /// Try to get the config object, and then return automatically the custom class object.
        /// </summary>
        /// <typeparam name="T">A custom class that inherit <see cref="ConfHelper"/> class.</typeparam>
        /// <param name="key">The config key (e.g. "projects", "app", ...)</param>
        /// <param name="configClass">The custom class object, or null if not found</param>
        /// <returns>True if found, false otherwis</returns>
        public bool TryGetConfig<T>(string key, out T? configClass) where T : ConfHelper
        {
            configClass = null;
            if (!TryGetConfig(key, out CONFIG _configClass))
                return false;

            if(_configClass.HasCustomClass)
            {
                if(_configClass.ClassType == typeof(T))
                {
                    configClass = (T)_configClass.Class!;
                    return true;
                }
            }
            return false;
        }

        /// <summary>
        /// Load a config file. This should be mainly called by the engine. Use <see cref="LoadOrMake(string, string, string)"/> if possible.
        /// </summary>
        /// <param name="config_name">The config name, this will be used as "key" so it need to be UNIQUE.</param>
        /// <param name="config_path">The path to the .xml config file.</param>
        /// <returns>The XDocument if found, null otherwise.</returns>
        private XDocument? Load(string config_name, string config_path)
        {
            if (Configs.TryGetValue(config_name, out CONFIG value))
            {
                return value.Document;
            }

            if (File.Exists(config_path))
            {
                try
                {
                    XDocument config = XDocument.Load(config_path);

                    string? classNamespace = config.Root?.Attribute("customClass")?.Value;

                    // If className is not null, then this config SHOULD have a custom class as "helper"
                    if (classNamespace != null)
                    {
                        System.Type? classType = System.Type.GetType(classNamespace);

                        if(classType == null)
                        {
                            throw new Exception($"Couldn't find class '{classNamespace}'.");
                        }

                        if(!classType.IsSubclassOf(typeof(ConfHelper)))
                        {
                            throw new Exception($"Class '{classNamespace}' do not inherit from 'RPGCreator.Core.Services.ConfigurationService.ConfHelper'.");
                        }

                        ConfHelper? classInstance = (ConfHelper?)Activator.CreateInstance(classType);

                        if( classInstance != null )
                        {
                            CONFIG config_data_CS = new(config, config_path, classType, classInstance);
                            classInstance.LoadConf(config_data_CS);
                            Configs[config_name] = config_data_CS;
                            return config;
                        }
                        else
                        {
                            throw new Exception($"Class '{classNamespace}' cannot be created due to an unknown error.");
                        }
                    }

                    Configs[config_name] = new(config, config_path);
                    return config;
                }
                catch
                {
                    return null;
                }
            }

            return null;
        }

        /// <summary>
        /// Load a config file, or create it if no config file could be found.
        /// </summary>
        /// <param name="config_name">The config name, this will be used as "key" so it need to be UNIQUE.</param>
        /// <param name="config_path">The path to the .xml config file.</param>
        /// <param name="template">The template used if no file could be found.</param>
        /// <returns>The XDocument if found / created, null otherwise</returns>
        public XDocument? LoadOrMake(string config_name, string config_path, string template)
        {
            XDocument? loaded = Load(config_name, config_path);
            if (loaded == null)
            {
                XDocument document = XDocument.Parse(template);
                document.Save(config_path);
                loaded = Load(config_name, config_path);
            }

            return loaded;
        }

        public bool Save(string config_name)
        {
            if(Configs.TryGetValue(config_name, out CONFIG value))
            {
                if(value.HasCustomClass && value.Class != null)
                {
                    value.Class.Save();
                }
                return Save(value.Document, value.Filepath);
            }
            return false;
        }

        public bool Save(string config_name, string filepath)
        {
            if (Configs.TryGetValue(config_name, out CONFIG value))
            {
                if (value.HasCustomClass && value.Class != null)
                {
                    value.Class.Save(filepath);
                }
                return Save(value.Document, filepath);
            }
            return false;
        }

        public bool Save(XDocument document, string filepath)
        {
            document.Save(filepath);
            return true;
        }

        /// <summary>
        /// This class should ONLY be inherited for config helper.
        /// </summary>
        public abstract class ConfHelper : ObservableObject
        {
            protected CONFIG? Config;

            public void LoadConf(CONFIG config)
            {
                if(Config != null)
                {
                    return;
                }
                Config = config;
                OnLoadedConf();
            }

            public abstract void OnLoadedConf();
            public abstract void Save(string filepath = "");
        }

        


        public class StyleConf : ConfHelper
        {

            public override void OnLoadedConf()
            {
                return;
            }

            public override void Save(string filepath = "")
            {
                return;
            }
        }

    }

}
