// RPG Creator - Open-source RPG Engine.
// (c) 2026 Ward
// 
// This file is part of RPG Creator and is distributed under the Apache 2.0 License.
// You are free to use, modify, and distribute this file under the terms of the Apache 2.0 License.
// See LICENSE for details.
// 
// ---
// 
// Ce fichier fait partie de RPG Creator et est distribué sous licence Apache 2.0.
// Vous êtes libre de l'utiliser, de le modifier et de le distribuer sous les termes de la licence Apache 2.0.
// Voir LICENSE pour plus de détails.
// 
// Contact:
// => Mail: Ward727a@gmail.com
//    Please use this object: "RPG Creator [YourObject]"
// => Discord: ward727
// 
// For urgent inquiries, sending both an email and a message on Discord is highly recommended for a quicker response.

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace UiPropertiesGenerators;

[Generator]
public class ContextGenerator : IIncrementalGenerator
{
    private static DiagnosticDescriptor _descriptor = new DiagnosticDescriptor(
        id: "SG001",
        title: "Debug Log",
        messageFormat: "Log message: {0}",
        category: "SourceGenerator",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static IncrementalGeneratorInitializationContext _context;

    private record struct AttributeData(string DisplayName = "", string Description = "", string Path = "", bool IsReadOnly = false);
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        _context = context;
        
#if DEBUG
        if (!Debugger.IsAttached)
        {
            Debugger.Launch();
        }
#endif
        var classDeclaration = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { Members.Count: > 0},
                transform: static (ctx, token) => GetSemanticTargetForGeneration(ctx, token))
            .Where(static m => m is not null);
        
        context.RegisterSourceOutput(classDeclaration.Collect(), static (spc, sources) =>
        {
            Execute(spc, sources);
        });
    }

    private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext ctx, CancellationToken token)
    {

        var classDeclaration = (ClassDeclarationSyntax)ctx.Node;
        var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDeclaration, token) as INamedTypeSymbol;

        if (classSymbol == null) return null;
        
        bool containsTargetAttribute = ContainsTargetedAttribute(classSymbol);
        
        return containsTargetAttribute ? classSymbol : null;
    }

    private static bool ContainsTargetedAttribute(INamedTypeSymbol symbol)
    {
        return symbol.GetMembers().Any(m => m.GetAttributes().Any(attribute =>
            attribute?.AttributeClass?.Name == "GuiControlPropertyAttribute"));
    }

    private static void Execute(SourceProductionContext spc, ImmutableArray<INamedTypeSymbol?> sources)
    {
        foreach (var source in sources)
        {
            if (source is null) continue;
            
            var sourceCode = GenerateClass(spc, source);
            
            spc.AddSource($"{source.Name}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }
    }
    
    private static string GenerateClass(SourceProductionContext spc, INamedTypeSymbol classSymbol)
    {
        var stringWriter = new StringWriter(new StringBuilder());
        using var sb = new IndentedTextWriter(stringWriter, "    ");
        
        GenerateHeader(classSymbol, sb);
        
        sb.WriteLine("{");
        {
            sb.WriteLine("// This partial class was auto-generated by the ContextGenerator source generator. Do not modify this file directly.");
            sb.Indent++;
            
            var className = classSymbol.Name;
            
            sb.WriteLine($"public partial class {className} : IHasControlProperties");
            sb.WriteLine("{");
            
            var properties = classSymbol.GetMembers().OfType<IFieldSymbol>()
                .Where(p => p.GetAttributes().Any(a => a.AttributeClass?.Name == "GuiControlPropertyAttribute"));
            
            spc.ReportDiagnostic(Diagnostic.Create(_descriptor, Location.None, $"Found {properties.Count()} properties in class {className}"));
            Console.WriteLine("Properties: ");
            
            var editableGeneratedProperties = new HashSet<string>();
            var readOnlyGeneratedProperties = new HashSet<string>();
            
            #region Properties
            {
                sb.Indent++;

                foreach (var property in properties)
                {
                    Console.WriteLine($"  - {property.Name}");
                    var attributeData = GetAttributeData(property);
                    
                    var propertySimpleVarName = property.Name.TrimStart('_');
                    propertySimpleVarName = propertySimpleVarName.Substring(0, 1).ToUpper(CultureInfo.InvariantCulture) + propertySimpleVarName.Substring(1);


                    if (attributeData.IsReadOnly)
                    {
                        GenerateReadOnlyMethods(sb, property, attributeData, propertySimpleVarName);

                        readOnlyGeneratedProperties.Add(propertySimpleVarName);
                    }
                    else
                    {
                        GenerateEditablePropertyMethods(property, className, sb, attributeData, propertySimpleVarName);

                        editableGeneratedProperties.Add(propertySimpleVarName);
                    }
                }
                
                sb.WriteLine(CreateGetEditableProperties(editableGeneratedProperties));
                sb.WriteLine();
                
                sb.WriteLine(CreateGetReadOnlyProperties(readOnlyGeneratedProperties));
                sb.WriteLine();
            }
            #endregion
            
            sb.WriteLine(CreateGetAllProperties(editableGeneratedProperties, readOnlyGeneratedProperties));
            sb.WriteLine();
            sb.WriteLine(CreateCounts(editableGeneratedProperties, readOnlyGeneratedProperties));
            sb.WriteLine();
            
            sb.Indent--;
            sb.WriteLine("}");
        }
        sb.Indent--;
        sb.WriteLine("}");
        return stringWriter.ToString();
    }

    private static void GenerateReadOnlyMethods(IndentedTextWriter sb, IFieldSymbol property, AttributeData attributeData,
        string propertySimpleVarName)
    {
        sb.WriteLine(CreateGetMethod(property));
        sb.WriteLine();
                    
        sb.WriteLine(CreatePartialGetMethod(property));
        sb.WriteLine();
                    
        sb.WriteLine(CreateReadOnlyProperty(property, attributeData, propertySimpleVarName));
        sb.WriteLine();
    }

    private static void GenerateEditablePropertyMethods(IFieldSymbol property, string className, IndentedTextWriter sb,
        AttributeData attributeData, string propertySimpleVarName)
    {
        if (property.IsReadOnly || property.IsConst)
        {
            throw new ArgumentException(
                $"Field '{property.Name}' in class '{className}' is marked with ControlEditablePropertyAttribute but is read-only, or const. Only non-readonly fields can be used as editable properties.");
        }

        sb.WriteLine(CreateGetMethod(property));
        sb.WriteLine();

        sb.WriteLine(CreatePartialGetMethod(property));
        sb.WriteLine();

        sb.WriteLine(CreateSetMethod(property));
        sb.WriteLine();

        sb.WriteLine(CreatePartialSetMethod(property));
        sb.WriteLine();

        sb.WriteLine(CreateValidateMethod(property));
        sb.WriteLine();

        sb.WriteLine(CreatePartialValidateMethod(property));
        sb.WriteLine();

        sb.WriteLine(CreateCoerceMethod(property));
        sb.WriteLine();

        sb.WriteLine(CreatePartialCoerceMethod(property));
        sb.WriteLine();

        sb.WriteLine(CreateEditableProperty(property, attributeData, propertySimpleVarName));
        sb.WriteLine();
    }

    private static void GenerateHeader(INamedTypeSymbol classSymbol, IndentedTextWriter sb)
    {
        var baseNamespace = classSymbol.ContainingNamespace.ToDisplayString(
            SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle
                .OmittedAsContaining));

        sb.WriteLine("// <auto-generated/>");
        sb.WriteLine("#nullable enable");
        sb.WriteLine("using System;");
        sb.WriteLine("using System.Collections.Generic;");
        sb.WriteLine("using RPGCreator.SDK.GameUI;");
        sb.WriteLine("using RPGCreator.SDK.GameUI.Interfaces;");
        sb.WriteLine("using RPGCreator.SDK.Types;");
        sb.WriteLine("using RPGCreator.Shared.Types;");
        sb.WriteLine();
        sb.WriteLine($"namespace {baseNamespace}");
    }

    private static AttributeData GetAttributeData(IFieldSymbol property)
    {
        var data = new AttributeData();
    
        var targetAttribute = property.GetAttributes().FirstOrDefault(a => 
            a.AttributeClass?.Name == "GuiControlPropertyAttribute");

        if (targetAttribute == null) 
            return data;

        return Enumerable.Aggregate(targetAttribute.NamedArguments, data, (current, arg) => arg.Key switch
        {
            "Description" when arg.Value.Value is string namedDesc => current with { Description = namedDesc.Replace("\"", "\\\"") },
            "Path" when arg.Value.Value is string namedPath => current with { Path = namedPath.Replace("\"", "\\\"") },
            "IsReadOnly" when arg.Value.Value is bool isReadOnly => current with { IsReadOnly = isReadOnly },
            "DisplayName" when arg.Value.Value is string displayName => current with { DisplayName = displayName.Replace("\"", "\\\"") },
            _ => current
        });
    }

    private static string CreateGetMethod(IFieldSymbol property)
    {
        return $$"""
                 private object? _uiGet{{property.Name}}()
                 {
                    var currentValue = {{property.Name}};
                    UiGet{{property.Name}}(ref currentValue);
                    return currentValue;
                 }
                 """;
    }

    private static string CreatePartialGetMethod(IFieldSymbol property)
    {
        return $"partial void UiGet{property.Name}(ref {property.Type} returnValue);";
    }

    private static string CreateSetMethod(IFieldSymbol property)
    {
        return $$"""
                 private void _uiSet{{property.Name}}(object? value)
                 {
                    var newValue = value;
                    UiSet{{property.Name}}(ref newValue);
                    if (newValue is {{property.Type.ToString().TrimEnd('?')}} typedValue)
                    {
                        if(typedValue == {{property.Name}}) return;
                        {{property.Name}} = typedValue;
                    }
                 }
                 """;
    }
    
    private static string CreatePartialSetMethod(IFieldSymbol property)
    {
        return $"partial void UiSet{property.Name}(ref object? newValue);";
    }

    private static string CreateValidateMethod(IFieldSymbol property)
    {
        return $$"""
                    private bool _uiValidate{{property.Name}}(object? valueToValidate)
                    {
                        var isValid = true;
                        UiValidate{{property.Name}}(valueToValidate, ref isValid);
                        return valueToValidate is {{property.Type.ToString().TrimEnd('?')}} && isValid;
                    }
                 """;
    }
    
    private static string CreatePartialValidateMethod(IFieldSymbol property)
    {
        return $"partial void UiValidate{property.Name}(object? valueToValidate, ref bool isValid);";
    }

    private static string CreateCoerceMethod(IFieldSymbol property)
    {
        return $$"""
                    private object? _uiCoerce{{property.Name}}(object? valueToCoerce)
                    {
                        var newValue = valueToCoerce;
                        UiCoerce{{property.Name}}(ref valueToCoerce);
                        return newValue;
                    }
                 """;
    }
    
    private static string CreatePartialCoerceMethod(IFieldSymbol property)
    {
        return $"partial void UiCoerce{property.Name}(ref object? valueToCoerce);";
    }
    
    private static string CreateEditableProperty(IFieldSymbol property, AttributeData data, string varName)
    {
        
        
        return $"""
                 private EditableControlPropertyDescriptor? _{property.Name}Property__cache;
                 
                 public EditableControlPropertyDescriptor {varName}Property => _{property.Name}Property__cache ??= new EditableControlPropertyDescriptor(
                    name: "{(string.IsNullOrEmpty(data.DisplayName) ? varName : data.DisplayName)}",
                    type: typeof({property.Type.ToString().TrimEnd('?')}),
                    getter: _uiGet{property.Name}, 
                    path: PipedPath.Parse("{(!string.IsNullOrWhiteSpace(data.Path) ? $"{data.Path}" : "Properties")}"), 
                    description: "{(!string.IsNullOrWhiteSpace(data.Description) ? $"{data.Description}" : "")}",
                    setter: _uiSet{property.Name},
                    validate: _uiValidate{property.Name},
                    coerce: _uiCoerce{property.Name}
                 );
                 """;
    }

    private static string CreateReadOnlyProperty(IFieldSymbol property, AttributeData data, string varName)
    {
        
        return $"""
                    private ReadOnlyControlPropertyDescriptor? _{property.Name}Property__cache;
                    
                    public ReadOnlyControlPropertyDescriptor {varName}Property => _{property.Name}Property__cache ??= new ReadOnlyControlPropertyDescriptor(
                        name: "{(string.IsNullOrEmpty(data.DisplayName) ? varName : data.DisplayName)}",
                        type: typeof({property.Type.ToString().TrimEnd('?')}),
                        getter: _uiGet{property.Name}, 
                        path: PipedPath.Parse("{(!string.IsNullOrWhiteSpace(data.Path) ? $"{data.Path}" : "Properties")}"), 
                        description: "{(!string.IsNullOrWhiteSpace(data.Description) ? $"{data.Description}" : "")}"
                    );
                 """;
    }

    private static string CreateGetEditableProperties(HashSet<string> generatedProperties)
    {
        return $$"""

                 public IEnumerable<EditableControlPropertyDescriptor> GetEditableProperties()
                 {
                    return [
                        {{string.Join(",\n", generatedProperties.Select(p => $"{p}Property"))}}
                    ];
                 }

                 """;
    }
    
    private static string CreateGetReadOnlyProperties(HashSet<string> generatedProperties)
    {
        return $$"""
                 public IEnumerable<ReadOnlyControlPropertyDescriptor> GetReadOnlyProperties()
                 {
                    return [
                        {{string.Join(",\n", generatedProperties.Select(p => $"{p}Property"))}}
                    ];
                 }

                 """;
    }

    private static string CreateGetAllProperties(HashSet<string> editable, HashSet<string> readonlyProperties)
    {
        return $$"""
                 public IEnumerable<ControlPropertyDescriptor> GetAllProperties()
                 {
                    return [
                        {{string.Join(",\n", editable.Select(p => $"{p}Property"))}},
                        {{string.Join(",\n", readonlyProperties.Select(p => $"{p}Property"))}}
                    ];
                 }

                 """;
    }
    
    private static string CreateCounts(HashSet<string> editable, HashSet<string> readonlyProperties)
    {
        return $"""
                 public int EditablePropertyCount => {editable.Count};
                 public int ReadOnlyPropertyCount => {readonlyProperties.Count};
                 public int TotalPropertyCount => {editable.Count + readonlyProperties.Count};
                 """;
    }
    
}