<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="plugins">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="plugin" maxOccurs="unbounded" minOccurs="0">
			        <xs:complexType>
                        <xs:sequence>
                          <!-- define the unique name of the plugin -->
                          <xs:element name="unique" type="xs:string" minOccurs="1" maxOccurs="1"/>
                          <!-- define the name of the plugin -->
                          <xs:element name="name" type="xs:string" minOccurs="1"/>
                          <!-- define the description of the plugin (not obligatory) -->
                          <xs:element name="description" type="xs:string" minOccurs="0"/>
                          <!-- define the version of the plugin -->
                          <xs:element name="version" type="xs:string" minOccurs="1"/>
                          <!-- define if the plugin is enabled or not (reserved by the engine) -->
                          <xs:element name="enabled" type="xs:boolean" default="false" minOccurs="1"/>
                          <!-- define the authors of the plugin -->
                          <xs:element name="authors" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="author" type="xs:string" maxOccurs="unbounded" minOccurs="1"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <!-- define what engine version the plugin support -->
                          <xs:element name="supported-versions" minOccurs="1" maxOccurs="1">
				              <xs:complexType>
                              <xs:sequence>
                                <xs:element name="version" type="xs:string" maxOccurs="unbounded" minOccurs="1"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <!-- define what plugin(s) this plugin need to be enabled -->
                          <xs:element name="dependencies" maxOccurs="1" minOccurs="0">

				              <xs:complexType>
                              <xs:sequence>
                                <xs:element name="plugin" type="xs:string" maxOccurs="unbounded" minOccurs="1"/>
                              </xs:sequence>
                            </xs:complexType>
                
                          </xs:element>
                          <!-- define what languages is supported by the plugin -->
                          <xs:element name="languages" maxOccurs="1" minOccurs="0">

                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="lang" maxOccurs="unbounded" minOccurs="1">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:enumeration value="FR-fr"/>
                                      <xs:enumeration value="EN-en"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                
                          </xs:element>
                          <!-- define where the config file for this plugin can be found at. reserved by the engine)
                          as config file need to be at the root of the plugin folder, it can be used to find the folder of the plugin too -->
                          <xs:element name="config" type="xs:string" maxOccurs="1" minOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

          <!-- define the version of the editor the file was created in (reserved by the engine) -->
        <xs:attribute name="version" type="xs:string" use="required"/>
    </xs:complexType>
    
  </xs:element>
</xs:schema>