<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:element name="Plugins">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Plugin" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" minOccurs="1"/>
              <xs:element name="Description" type="xs:string" minOccurs="0"/>
              <xs:element name="Version" type="xs:string" minOccurs="1"/>
              <xs:element name="Enabled" type="xs:boolean" default="false"/>
              <xs:element name="Authors" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Author" type="xs:string" maxOccurs="unbounded" minOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="EditorVersions" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Version" type="xs:string" maxOccurs="unbounded" minOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>

      <xs:attribute name="version" type="xs:string" use="required"/>
    </xs:complexType>
    
  </xs:element>
  
</xs:schema>