// RPG Creator - Open-source RPG Engine.
// (c) 2026 Ward
// 
// This file is part of RPG Creator and is distributed under the Apache 2.0 License.
// You are free to use, modify, and distribute this file under the terms of the Apache 2.0 License.
// See LICENSE for details.
// 
// ---
// 
// Ce fichier fait partie de RPG Creator et est distribué sous licence Apache 2.0.
// Vous êtes libre de l'utiliser, de le modifier et de le distribuer sous les termes de la licence Apache 2.0.
// Voir LICENSE pour plus de détails.
// 
// Contact:
// => Mail: Ward727a@gmail.com
//    Please use this object: "RPG Creator [YourObject]"
// => Discord: ward727
// 
// For urgent inquiries, sending both an email and a message on Discord is highly recommended for a quicker response.

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using RPGCreator.SDK;
using RPGCreator.SDK.Assets.Definitions.Blueprints;
using RPGCreator.SDK.Graph;
using RPGCreator.SDK.Graph.CompilerLogic;
using RPGCreator.SDK.Graph.LOGIC;
using RPGCreator.SDK.Types;
using RPGCreator.UI.Content.Blueprint;

namespace RPGCreator.UI.Services;

public class BpCompilerService : IBpCompilerService
{
    public Result<string> Build(string blueprintFilePath)
    {
        return Result<string>.Fail("BUILDING FROM A FILE PATH IS NOT IMPLEMENTED YET");
    }

    public Result<string> Build(object blueprintData)
    {
        if(blueprintData is NodeEditorViewModel vmData)
            return Build(vmData);
        else if(blueprintData is BlueprintCompilerData compiledData)
            return Build(compiledData);
        else if(blueprintData is BlueprintData bpData)
            return Build(bpData);
        else
            throw new ArgumentException("Unsupported blueprint data type");
    }

    private Result<string> Build(BlueprintData blueprintData)
    {
        // Ngl: It's a VERY dirty way of doing it, but it works for now. 
        return Build(NodeEditorViewModel.CreateFromData(blueprintData));
    }

    private Result<string> Build(BlueprintCompilerData data)
    {
        return CodeCompiler.CompileToCSharp(data);
    }
    
    private Result<string> Build(NodeEditorViewModel vm)
    {
        var bpData = new BlueprintCompilerData()
        {
            Id = vm.CurrentId,
        };

        foreach (var nodeViewModel in vm.Nodes)
        {
            bpData.Nodes.Add(nodeViewModel.NodeLogic);
        }

        foreach (var connectionViewModel in vm.Connections)
        {
            var source = connectionViewModel.Source;
            var target = connectionViewModel.Target;
            var sourceConnectorId = source.Id;
            var targetConnectorId = target.Id;
            var sourceNodeId = source.NodeId;
            var targetNodeId = target.NodeId;
            bpData.Connections.Add(new ConnectionLogic(sourceConnectorId, targetConnectorId, sourceNodeId, targetNodeId));
        }

        foreach (var parameterItem in vm.ParametersVm.ParametersCache.Items.Where(p => !p.IsArgument))
        {
            bpData.Parameters.Add(parameterItem);
        }

        foreach (var argumentItem in vm.ParametersVm.ParametersCache.Items.Where(p => p.IsArgument))
        {
            bpData.Arguments.Add(argumentItem);
        }

        return Build(bpData);
    }

    public async Task<Result<byte[]>> CompileAllBlueprints(string blueprintFolder = "", IProgress<float>? progress = null)
    {
        string assemblyName = $"RPGCreator.Generated.Blueprints_{DateTime.Now:yyyyMMdd_HHmm}";
        var buildGlobalResult = BuildGlobalBlueprintCode(blueprintFolder);
        
        if(buildGlobalResult.IsFailure)
            return Result<byte[]>.Fail(buildGlobalResult.Error);
        
        List<string> dataToCompile = buildGlobalResult.Value.referencedBlueprints;
        dataToCompile.Add(buildGlobalResult.Value.sourceCode);

        return await CodeCompiler.CompileToDll(assemblyName, dataToCompile.ToArray(),
            Path.Combine(RpgEnv.Path.ApplicationData, "compiled_blueprints.dll"), [
                typeof(RegistryServices).Assembly.Location,
                typeof(BaseBpCompiledLogic).Assembly.Location
            ],
            progress: progress);
    }
    
    public Result<(string sourceCode, List<string> referencedBlueprints)> BuildGlobalBlueprintCode(string blueprintFolder = "")
    {
        List<string> referencedBlueprints = [];
        var formatBpFile = Path.Combine(blueprintFolder, "{0}.cs");
        const string format_bp_class = "bp_class_{0}";
        using var stringWriter = new StringWriter();

        using (var indentedWriter = new IndentedTextWriter(stringWriter, "    "))
        {
            indentedWriter.WriteLine("// THIS FILE WAS AUTO-GENERATED BY THE RPG CREATOR ENGINE");
            indentedWriter.WriteLine("// ANY CHANGES MADE TO THIS FILE WILL BE LOST!");
            indentedWriter.WriteLine();
            indentedWriter.WriteLine("using System;");
            indentedWriter.WriteLine("using System.Runtime.CompilerServices;");
            indentedWriter.WriteLine("using RPGCreator.SDK;");
            indentedWriter.WriteLine("using RPGCreator.SDK.Logging;");
            indentedWriter.WriteLine();
            indentedWriter.WriteLine("namespace RPGCreator.SDK.Graph.Blueprints;");
            indentedWriter.WriteLine();
            indentedWriter.WriteLine("public class GlobalBlueprint");
            indentedWriter.WriteLine("{");
            indentedWriter.Indent++;
            {
                indentedWriter.WriteLine();
                indentedWriter.WriteLine("[ModuleInitializer]");
                indentedWriter.WriteLine("public static void Initialize()");
                indentedWriter.WriteLine("{");
                indentedWriter.Indent++;
                {
                    indentedWriter.WriteLine("Logger.Info(\"Initializing global blueprint logic...\");");
                    indentedWriter.WriteLine();
                    indentedWriter.WriteLine("new GlobalBlueprint().RegisterBlueprints();");
                }
                indentedWriter.Indent--;
                indentedWriter.WriteLine("}");
                indentedWriter.WriteLine();
                indentedWriter.WriteLine("public void RegisterBlueprints()");
                indentedWriter.WriteLine("{");
                indentedWriter.Indent++;
                {
                    indentedWriter.WriteLine();

                    foreach (var blueprint in RegistryServices.Blueprint.GetAllBlueprints())
                    {
                        var fileName = string.Format(formatBpFile, blueprint.Id);
                        var className = string.Format(format_bp_class, blueprint.Id);

                        if (!File.Exists(fileName))
                        {
                            indentedWriter.WriteLine(
                                $"// WARNING: Blueprint file '{fileName}' does not exist. Skipping registration for blueprint '{blueprint.Name}' ({blueprint.Id})");
                            indentedWriter.WriteLine(
                                $"Logger.Error(\"Blueprint file '{fileName}' does not exist for blueprint '{blueprint.Name}' ({blueprint.Id})\");");
                        }
                        else
                        {
                            referencedBlueprints.Add(fileName);
                            indentedWriter.WriteLine(
                                $"RegistryServices.Blueprint.RegisterBlueprintLogic(Ulid.Parse(\"{blueprint.Id}\"), new {className}()).OnFailure(e => Logger.Error(e));");
                        }

                        indentedWriter.WriteLine();
                    }
                }
                indentedWriter.Indent--;
                indentedWriter.WriteLine("}");
            }
            indentedWriter.Indent--;
            indentedWriter.WriteLine("}");
        };
        
        return Result<(string, List<string>)>.Ok((stringWriter.ToString(), referencedBlueprints));
    }
}