<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <TargetFramework>net8.0</TargetFramework>
      <OutputPath>../../RPGCreator.UI/Assets/Modules/$(AssemblyName)/</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <TargetFramework>net8.0</TargetFramework>
      <OutputPath>../../RPGCreator.UI/Assets/Modules/$(AssemblyName)/</OutputPath>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\RPGCreator.SDK.EditorUI\RPGCreator.SDK.EditorUI.csproj">
          <Private>false</Private>
          <ExcludeAssets>runtime</ExcludeAssets>
      </ProjectReference>
      <ProjectReference Include="..\..\RPGCreator.SDK\RPGCreator.SDK.csproj">
        <Private>false</Private>
        <ExcludeAssets>runtime</ExcludeAssets>
      </ProjectReference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="11.3.6" />
    </ItemGroup>

</Project>
