using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace RPGCreator.Generators
{
    /// <summary>
    /// This source generator creates context classes for methods marked with the ExposeToPluginAttribute.<br/>
    /// These context classes group methods by their specified region and provide a structured way to access them from CSharp modules.
    /// </summary>
    [Generator]
    public class ContextGenerator: IIncrementalGenerator 
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax { Members.Count: > 0 },
                    transform: static (ctx, token) => GetSemanticTargetForGeneration(ctx, token))
                .Where(static m => m is not null);

            context.RegisterSourceOutput(classDeclarations.Collect(), static (spc, sources) => Execute(spc, sources));
        }
        
        private static bool IsTargetSymbol(INamedTypeSymbol symbol)
        {
            return symbol.GetMembers().Any(m => m.GetAttributes().Any(a => 
                a.AttributeClass?.Name == "ExposeToPluginAttribute" || 
                a.AttributeClass?.Name == "ExposePropToPluginAttribute" || 
                a.AttributeClass?.Name == "ExposeEventToPluginAttribute"));
        }

        private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax c && c.Members.Count > 0;
        }

        private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context, System.Threading.CancellationToken token)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration, token) as INamedTypeSymbol;
    
            if (classSymbol == null) return null;

            bool containsTargetAttribute = classSymbol.GetMembers().Any(m => m.GetAttributes().Any(a => 
                a.AttributeClass?.Name.Contains("ExposeToPlugin") == true ||
                a.AttributeClass?.Name.Contains("ExposePropToPlugin") == true ||
                a.AttributeClass?.Name.Contains("ExposeEventToPlugin") == true));

            return containsTargetAttribute ? classSymbol : null;
        }

        private static void Execute(SourceProductionContext context, System.Collections.Immutable.ImmutableArray<INamedTypeSymbol?> classSymbols)
        {
            var allRegions = new HashSet<string>();
            HashSet<string> generatedContexts = new();

            foreach (var symbol in classSymbols)
            {
                if (symbol == null) continue;

                (string sourceCode, HashSet<string> regions) = GenerateContextClasses(symbol);
                context.AddSource($"{symbol.Name}Context.g.cs", SourceText.From(sourceCode, Encoding.UTF8));

                allRegions.UnionWith(regions);
            }

            foreach (var r in allRegions)
            {
                generatedContexts.Add($"{r.Replace(".", "").Replace(" ", "")}Context");
            }

            if (allRegions.Any())
            {
                var extensionCode = GenerateFluentExtensions(allRegions, generatedContexts);
                context.AddSource("UiExtensionExtensions_Global.g.cs", SourceText.From(extensionCode, Encoding.UTF8));
            }
        }

        private static (string sourceCode, HashSet<string> regions) GenerateContextClasses(INamedTypeSymbol classSymbol)
        {
            var sb = new StringBuilder();
            var baseNamespace = "RPGCreator.UI.Contexts";
            
            HashSet<string> regions = new();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Avalonia.Controls;");
            sb.AppendLine($"namespace {baseNamespace}");
            sb.AppendLine("{");

            var methods = classSymbol.GetMembers().OfType<IMethodSymbol>()
                .Where(m => m.GetAttributes().Any(a => a.AttributeClass?.Name == "ExposeToPluginAttribute"));
            var properties = classSymbol.GetMembers().OfType<IPropertySymbol>()
                .Where(p => p.GetAttributes().Any(a => a.AttributeClass?.Name == "ExposePropToPluginAttribute"));
            var events = classSymbol.GetMembers().OfType<IEventSymbol>()
                .Where(e => e.GetAttributes().Any(a => a.AttributeClass?.Name == "ExposeEventToPluginAttribute"));

            // Combine all members
            var allMembers = methods.Select(m => new { 
                    Symbol = (ISymbol)m, 
                    Region = m.GetAttributes().First(a => a.AttributeClass.Name == "ExposeToPluginAttribute").ConstructorArguments[0].Value.ToString(),
                    Type = "Method"
                })
                .Concat(properties.Select(p => new { 
                    Symbol = (ISymbol)p, 
                    Region = p.GetAttributes().First(a => a.AttributeClass.Name == "ExposePropToPluginAttribute").ConstructorArguments[0].Value.ToString(),
                    Type = "Property"
                })
                .Concat(events.Select(e => new { 
                    Symbol = (ISymbol)e, 
                    Region = e.GetAttributes().First(a => a.AttributeClass.Name == "ExposeEventToPluginAttribute").ConstructorArguments[0].Value.ToString(),
                    Type = "Event"
            })));
            
            // Group by Region
            var groupedMembers = allMembers.GroupBy(x => x.Region);

            foreach (var group in groupedMembers)
            {
                string regionId = group.Key;
                regions.Add(regionId);
                
                string safeRegionName = regionId.Replace(".", "").Replace(" ", "");
                string contextName = $"{safeRegionName}Context";

                sb.AppendLine($"    /// <summary>Context for region: {regionId}</summary>");
                sb.AppendLine($"    public class {contextName}");
                sb.AppendLine("    {");
                
                // Make Fields
                foreach (var item in group.Where(x => x.Type == "Method"))
                {
                    var method = (IMethodSymbol)item.Symbol;
                    var paramTypes = string.Join(", ", method.Parameters.Select(p => p.Type.ToString()));
                    string actionType;
                    if (method.ReturnsVoid)
                    {
                        if (method.Parameters.Length == 0)
                        {
                            actionType = "Action";
                        }
                        else
                        {
                            actionType = $"Action<{paramTypes}>";
                        }
                    }
                    else
                    {
                        if(method.Parameters.Length == 0)
                        {
                            actionType = $"Func<{method.ReturnType}>";
                        }
                        else
                        {
                            actionType = $"Func<{paramTypes}, {method.ReturnType}>";
                        }
                    }
                    sb.AppendLine($"        private readonly {actionType} _{method.Name};");
                }

                // Make Property Fields
                foreach (var item in group.Where(x => x.Type == "Property"))
                {
                    var prop = (IPropertySymbol)item.Symbol;
                    var propType = prop.Type.ToString();
                    var attrArgs = prop.GetAttributes().First(a => a.AttributeClass.Name == "ExposePropToPluginAttribute").ConstructorArguments;
                    bool canSet = (bool)attrArgs[1].Value;

                    // Champ pour le Getter : Func<Type>
                    sb.AppendLine($"        private readonly Func<{propType}> _get{prop.Name};");

                    // Champ pour le Setter : Action<Type> (Seulement si CanSet)
                    if (canSet)
                    {
                        sb.AppendLine($"        private readonly Action<{propType}> _set{prop.Name};");
                    }
                }
                
                // Make Event Fields
                foreach (var item in group.Where(x => x.Type == "Event"))
                {
                    var evt = (IEventSymbol)item.Symbol;
                    var delegateType = evt.Type.ToString(); // ex: System.EventHandler
            
                    // On stocke les actions d'abonnement/désabonnement
                    sb.AppendLine($"        private readonly Action<{delegateType}> _add{evt.Name};");
                    sb.AppendLine($"        private readonly Action<{delegateType}> _remove{evt.Name};");
                }

                sb.AppendLine();
                
                // Make Config Class
                sb.AppendLine($"        /// <summary>Configuration object to initialize the context.</summary>");
                sb.AppendLine($"        public class Config");
                sb.AppendLine("        {");
                // A. Config pour Méthodes
                foreach (var item in group.Where(x => x.Type == "Method"))
                {
                    var method = (IMethodSymbol)item.Symbol;
                    var paramTypes = string.Join(", ", method.Parameters.Select(p => p.Type.ToString()));
                    string actionType = "";
                    if (method.ReturnsVoid)
                    {
                        if (method.Parameters.Length == 0)
                        {
                            actionType = "Action";
                        }
                        else
                        {
                            actionType = $"Action<{paramTypes}>";
                        }
                    }
                    else
                    {
                        if(method.Parameters.Length == 0)
                        {
                            actionType = $"Func<{method.ReturnType}>";
                        }
                        else
                        {
                            actionType = $"Func<{paramTypes}, {method.ReturnType}>";
                        }
                    }
                    // On utilise 'required' (C# 11) ou juste public pour forcer l'assignation
                    sb.AppendLine($"            public {actionType} {method.Name} {{ get; set; }} = null!;");
                }

                foreach (var item in group.Where(x => x.Type == "Property"))
                {
                    var prop = (IPropertySymbol)item.Symbol;
                    var propType = prop.Type.ToString();
                    bool canSet = (bool)prop.GetAttributes().First(a => a.AttributeClass.Name == "ExposePropToPluginAttribute").ConstructorArguments[1].Value;

                    sb.AppendLine($"            public Func<{propType}> Get{prop.Name} {{ get; set; }} = null!;");
                    if (canSet)
                    {
                        sb.AppendLine($"            public Action<{propType}> Set{prop.Name} {{ get; set; }} = null!;");
                    }
                }

                foreach (var item in group.Where(x => x.Type == "Event"))
                {
                    var evt = (IEventSymbol)item.Symbol;
                    var delegateType = evt.Type.ToString();
                    sb.AppendLine($"            public Action<{delegateType}> Add{evt.Name} {{ get; set; }} = null!;");
                    sb.AppendLine($"            public Action<{delegateType}> Remove{evt.Name} {{ get; set; }} = null!;");
                }

                sb.AppendLine("        }");
                sb.AppendLine();
                
                // Make Constructors
                sb.AppendLine($"        public {contextName}(Config config)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (config == null) throw new ArgumentNullException(nameof(config));");
                sb.AppendLine();
                
                // Assign Methods
                foreach (var item in group.Where(x => x.Type == "Method"))
                {
                    var method = (IMethodSymbol)item.Symbol;
                    sb.AppendLine($"            _{method.Name} = config.{method.Name};");
                }

                // Assign Properties
                foreach (var item in group.Where(x => x.Type == "Property"))
                {
                    var prop = (IPropertySymbol)item.Symbol;
                    bool canSet = (bool)prop.GetAttributes().First(a => a.AttributeClass.Name == "ExposePropToPluginAttribute").ConstructorArguments[1].Value;

                    sb.AppendLine($"            _get{prop.Name} = config.Get{prop.Name};");
                    if (canSet) sb.AppendLine($"            _set{prop.Name} = config.Set{prop.Name};");
                }

                // Assign Events
                foreach (var item in group.Where(x => x.Type == "Event"))
                {
                    var evt = (IEventSymbol)item.Symbol;
                    sb.AppendLine($"            _add{evt.Name} = config.Add{evt.Name};");
                    sb.AppendLine($"            _remove{evt.Name} = config.Remove{evt.Name};");
                }

                sb.AppendLine("        }");

                // Make Methods
                foreach (var item in group.Where(x => x.Type == "Method"))
                {
                    var method = (IMethodSymbol)item.Symbol;
                    string docXml = method.GetDocumentationCommentXml();

                    if (!string.IsNullOrWhiteSpace(docXml))
                    {
                        try
                        {
                            var xElement = XElement.Parse(docXml);
                            var summary = xElement.Element("summary")?.Value.Trim();

                            if (!string.IsNullOrWhiteSpace(summary))
                            {
                                sb.AppendLine("        /// <summary>");

                                var lines = summary.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
                                foreach (var line in lines)
                                {
                                    sb.AppendLine($"        /// {line.Trim()}");
                                }

                                sb.AppendLine("        /// </summary>");
                            }

                            var paramsElements = xElement.Elements("param");
                            foreach (var param in paramsElements)
                            {
                                var paramName = param.Attribute("name")?.Value;
                                var paramDesc = param.Value.Trim();
                                if (!string.IsNullOrWhiteSpace(paramName) && !string.IsNullOrWhiteSpace(paramDesc))
                                {
                                    sb.AppendLine($"        /// <param name=\"{paramName}\">{paramDesc}</param>");
                                }
                            }

                            var returnsElement = xElement.Element("returns");
                            if (returnsElement != null)
                            {
                                var returnsDesc = returnsElement.Value.Trim();
                                if (!string.IsNullOrWhiteSpace(returnsDesc))
                                {
                                    sb.AppendLine($"        /// <returns>{returnsDesc}</returns>");
                                }
                            }
                        }
                        catch
                        {
                            // IGNORED
                        }
                    }

                    var obsoleteAttr = method.GetAttributes()
                        .FirstOrDefault(a =>
                            a.AttributeClass?.Name == "ObsoleteAttribute" &&
                            a.AttributeClass?.ContainingNamespace?.Name == "System");

                    if (obsoleteAttr != null)
                    {
                        string message = null;
                        bool isError = false;

                        if (obsoleteAttr.ConstructorArguments.Length > 0)
                        {
                            message = obsoleteAttr.ConstructorArguments[0].Value?.ToString();
                        }
                        
                        if (obsoleteAttr.ConstructorArguments.Length > 1)
                        {
                            isError = (bool)obsoleteAttr.ConstructorArguments[1].Value!;
                        }
                        
                        if (message != null)
                        {
                            string safeMessage = message.Replace("\"", "\\\"");
                            string errorBool = isError.ToString().ToLower();
                            sb.AppendLine($"        [Obsolete(\"{safeMessage}\", {errorBool})]");
                        }
                        else
                        {
                            sb.AppendLine("        [Obsolete]");
                        }
                    }
                    var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
                    var callArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
                    var returnType = method.ReturnsVoid ? "void" : method.ReturnType.ToString();

                    sb.AppendLine($"        public {returnType} {method.Name}({parameters})");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            {(method.ReturnsVoid ? "" : "return ")}_{method.Name}({callArgs});");
                    sb.AppendLine("        }");
                }

                // Make Properties
                foreach (var item in group.Where(x => x.Type == "Property"))
                {
                    var prop = (IPropertySymbol)item.Symbol;
                    var propType = prop.Type.ToString();
                    bool canSet = (bool)prop.GetAttributes().First(a => a.AttributeClass.Name == "ExposePropToPluginAttribute").ConstructorArguments[1].Value;

                    sb.AppendLine($"        public {propType} {prop.Name}");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            get => _get{prop.Name}();");
                    if (canSet)
                    {
                        sb.AppendLine($"            set => _set{prop.Name}(value);");
                    }
                    sb.AppendLine("        }");
                }
                
                // Make Events
                foreach (var item in group.Where(x => x.Type == "Event"))
                {
                    var evt = (IEventSymbol)item.Symbol;
                    var delegateType = evt.Type.ToString();

                    // On génère un event proxy
                    sb.AppendLine($"        public event {delegateType} {evt.Name}");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            add => _add{evt.Name}(value);");
                    sb.AppendLine($"            remove => _remove{evt.Name}(value);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
                
                sb.AppendLine("    }"); // Class closure
                sb.AppendLine();
            }

            sb.AppendLine("}"); // Namespace closure
            return (sb.ToString(), regions);
        }

        private static string GenerateFluentExtensions(IEnumerable<string> regions, HashSet<string> generatedContexts)
        {
            var sb = new StringBuilder();
            var ns = "RPGCreator.UI.Extensions";
            var contextNs = "RPGCreator.UI.Contexts";
            
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine($"using {contextNs};");
            sb.AppendLine("using RPGCreator.SDK.Attributes;");
            sb.AppendLine("using RPGCreator.SDK.EditorUiService;");
            sb.AppendLine("using RPGCreator.SDK.Modules.UIModule;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Fluent extensions for IUiExtensionManager to access plugin contexts in a structured way.<br/>");
            sb.AppendLine("    /// Example usage: UiService.ExtensionManager.Editor().LeftPanel_Components((target, context) => { /* ... */ });");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static partial class UiExtensionExtensions_Generated");
            sb.AppendLine("    {");

            // Grouping by "main" scope (e.g., "Editor" for "Editor.EditorLeftPanel.Components") to create nested structs for better organization
            var groupedByScope = regions.Distinct().OrderBy(r => r).GroupBy(r => r.Split('.')[0]);

            foreach (var scopeGroup in groupedByScope)
            {
                var scopeName = scopeGroup.Key;
                var structName = $"{scopeName}Scope";
                
                // Extensions to access the context: ui.ExtensionManager.Editor() => returns EditorScope struct
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// Accessor for the {scopeName} scope, providing fluent methods to register extensions for its regions.");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        public static {structName} {scopeName}(this IUiExtensionManager manager) => new {structName}(manager);");
                sb.AppendLine();
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// Struct providing fluent methods to register extensions for the {scopeName} scope regions.<br/>");
                sb.AppendLine($"        /// Note: This struct should not be used directly. Use the extension method to access it instead (e.g., UiService.ExtensionManager.{scopeName}()).");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        public partial struct {structName}");
                sb.AppendLine("        {");
                sb.AppendLine("            private readonly IUiExtensionManager _manager;");
                sb.AppendLine($"            public {structName}(IUiExtensionManager manager) => _manager = manager;");
                if (generatedContexts.Contains($"{scopeName}Context"))
                {
                    // If there's a context that matches the scope name, we create a method to register extensions with that context: ui.ExtensionManager.Editor(callback)
                    sb.AppendLine("            /// <summary>");
                    sb.AppendLine($"            /// Registers an extension for the {scopeName} scope with a strongly-typed context callback.<br/>");
                    sb.AppendLine($"            /// This will apply to all regions under the {scopeName} scope.");
                    sb.AppendLine("            /// </summary>");
                    sb.AppendLine("             /// <param name=\"callback\">The callback to execute when the extension is applied. Provides the target control and a typed context.</param>");
                    sb.AppendLine();
                    sb.AppendLine($"            public {structName} Configure(Action<object, {scopeName}Context> callback)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                _manager.RegisterExtension(UIRegion.{scopeName}, (target, context) => {{");
                    sb.AppendLine($"                    if (context is {scopeName}Context typedContext) {{");
                    sb.AppendLine("                         callback(target, typedContext);");
                    sb.AppendLine("                    }");
                    sb.AppendLine("                });");
                    sb.AppendLine("                return this;");
                    sb.AppendLine("            }");
                }
                else
                {
                    sb.AppendLine("            /// <summary>");
                    sb.AppendLine($"            /// Registers an extension for the {scopeName} scope with a context callback.<br/>");
                    sb.AppendLine($"            /// This will apply to all regions under the {scopeName} scope.<br/>");
                    sb.AppendLine("             /// <remarks>");
                    sb.AppendLine("             /// No strongly-typed context is available for this scope, the context parameter will be an <see cref=\"object\"/> typed.<br/>");
                    sb.AppendLine("             /// To correct this, use the [ExposeToPlugin](<see cref=\"ExposeToPluginAttribute\"/>) attribute on at least one method/property/event of the scope with the scope name as region to generate a context class and get a typed context in this callback.");
                    sb.AppendLine("             /// </remarks>");
                    sb.AppendLine("            /// </summary>");
                    sb.AppendLine("             /// <param name=\"callback\">The callback to execute when the extension is applied. Provides the target control and a typed context.</param>");
                    sb.AppendLine();
                    sb.AppendLine($"            public {structName} Configure(Action<object, object?> callback)");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                _manager.RegisterExtension(UIRegion.{scopeName}, (target, context) => {{");
                    sb.AppendLine("                    callback(target, context);");
                    sb.AppendLine("                });");
                    sb.AppendLine("                return this;");
                    sb.AppendLine("            }");
                }

                // For each region in the scope, we create a method: ui.ExtensionManager.Editor().LeftPanel_Components(callback)
                foreach (var regionId in scopeGroup)
                {
                    // Cleaning the region name to create a valid method name (e.g., "EditorLeftPanel.Components" becomes "LeftPanel_Components")
                    var methodName = regionId.Contains(".") 
                        ? regionId.Substring(regionId.IndexOf('.') + 1).Replace(".", "_") 
                        : "Register";

                    string safeRegionName = regionId.Replace(".", "").Replace(" ", "");
                    string contextName = $"{safeRegionName}Context";

                    if (generatedContexts.Contains(contextName))
                    {
                        sb.AppendLine("            /// <summary>");
                        sb.AppendLine($"            /// Registers an extension for the {regionId} region with a strongly-typed context callback.");
                        sb.AppendLine("            /// </summary>");
                        sb.AppendLine("             /// <param name=\"callback\">The callback to execute when the extension is applied. Provides the target control and a typed context.</param>");
                        sb.AppendLine($"            public {structName} {methodName}(Action<object, {contextName}> callback)");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                _manager.RegisterExtension(UIRegion.{safeRegionName}, (target, context) => {{");
                        sb.AppendLine($"                    if (context is {contextName} typedContext) {{");
                        sb.AppendLine("                         callback(target, typedContext);");
                        sb.AppendLine("                    }");
                        sb.AppendLine("                });");
                        sb.AppendLine("                return this;");
                        sb.AppendLine("            }");
                    }
                }
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}