<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
    One for Windows with net8.0-windows TFM, one for MacOS with net8.0-macos and one with net8.0 TFM for Linux.-->
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RPGCreator.Core\RPGCreator.Core.csproj" />
    <ProjectReference Include="..\RPGCreator.UI\RPGCreator.UI.csproj" />
  </ItemGroup>
    <Target Name="CopyUIAssets" AfterTargets="Build">
        <ItemGroup>
            <!-- Tous les fichiers du dossier Assets de RPGCreator.UI -->
            <UIAssets Include="..\RPGCreator.UI\Assets\**\*.*" />
        </ItemGroup>

        <Copy SourceFiles="@(UIAssets)"
              DestinationFolder="$(OutputPath)Assets\%(RecursiveDir)"
              SkipUnchangedFiles="true" />
    </Target>

</Project>
